# Generated by Django 4.2 on 2023-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0002_nonfactoidquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoidDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq_id', models.TextField()),
                ('context', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField(default='')),
            ],
        ),
    ]
