# Generated by Django 4.2.3 on 2023-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0003_factoiddone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq_id', models.TextField()),
                ('context', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField(default='')),
            ],
        ),
    ]
