# Generated by Django 4.2.3 on 2023-11-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0004_automaticquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticquestion',
            name='score',
            field=models.TextField(default='3'),
        ),
    ]
