# Generated by Django 4.2.3 on 2023-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0005_automaticquestion_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleAutomatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq_id', models.TextField()),
                ('context', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField(default='')),
                ('score', models.TextField(default='3')),
            ],
        ),
    ]
